export const TOOL_FAQS = {
  'background-remover': [
    ['What is a background remover?', 'A background remover separates the subject from the background so you can export a clean image with transparency or a new solid backdrop.'],
    ['How does an AI background remover work?', 'AI background removal detects the subject, traces the edges, and removes the background automatically with far less manual cleanup.'],
    ['Is this background remover free?', 'Yes. You can remove background from image files for free directly in your browser.'],
    ['Can I make image transparent?', 'Yes. The tool can export a transparent PNG that keeps the subject and removes the background.'],
    ['Which image formats are supported?', 'Common formats like JPG, PNG, and WebP are supported on most uploads.'],
    ['Should I use PNG or JPG after background removal?', 'PNG is the best choice when you need transparency. JPG is better only when you want a solid background and smaller file size.'],
    ['Can I remove white background from image?', 'Yes. White backgrounds are a common use case for AI background removal and product cutout workflows.'],
    ['Can I use it for ecommerce product photos?', 'Yes. Transparent backgrounds are widely used for ecommerce listings, ads, and marketplace product pages.'],
    ['Does background removal reduce image quality?', 'A good background remover keeps the subject sharp, but the final quality also depends on the original file resolution.'],
    ['Can I remove photo background online on mobile?', 'Yes. The tool works in modern mobile browsers as well as desktop browsers.'],
    ['Is the output a transparent PNG?', 'Yes. Transparent PNG is the standard export when you need a clean background-free image.'],
    ['Can I use the result on Amazon or Etsy?', 'Yes. Transparent product images are useful for Amazon, Etsy, Shopify, and other ecommerce platforms.'],
    ['Do uploaded files stay on the site permanently?', 'Files are processed for the task and are not intended for permanent storage on the platform.'],
    ['What is the difference between manual editing and AI background removal?', 'Manual editing gives pixel-level control but takes longer. AI background removal is much faster for most product, portrait, and marketing images.'],
    ['Which images work best with background removal?', 'Clear subjects with good edge contrast, such as product photos, portraits, and isolated objects, usually give the cleanest results.'],
  ],
  'edit-pdf': [
    ['Can I edit PDF files online without Adobe?', 'Yes. You can add text and basic edits to PDFs in your browser without Adobe Acrobat.'],
    ['Do I need to create an account?', 'No. You can use the tool without signup for normal editing workflows.'],
    ['Will my edited PDF be downloadable?', 'Yes. After editing, you can download the updated PDF file directly.'],
  ],
  'favicon-generator': [
    ['Which formats can I upload for favicon generation?', 'You can upload JPG, PNG, WebP, and SVG images.'],
    ['Does the tool generate all standard favicon sizes?', 'Yes. It generates common favicon, Apple touch, and Android/PWA icon sizes.'],
    ['Can I download everything in one file?', 'Yes. The tool packages all generated files into one ZIP for quick download.'],
  ],
  'image-compressor': [
    ['What is an image compressor?', 'An image compressor reduces image file size while keeping the visual detail useful for websites, social media, and sharing.'],
    ['How does online image compression work?', 'The tool analyzes the image, applies browser-side optimization, and creates a smaller file that is ready to download.'],
    ['How much can I reduce image size?', 'The result depends on the original format, resolution, and image detail. JPG files usually shrink the most, while PNG and WebP results vary based on transparency and texture.'],
    ['Does compression reduce quality?', 'Small reductions are usually hard to notice on screen, especially for web use. Stronger compression can reduce quality more, so the goal is to keep the file small and still usable.'],
    ['Can I compress JPG, PNG, and WebP files?', 'Yes, this free image compressor supports JPG, PNG, and WebP images directly in the browser without signup.'],
    ['Which format is best after compression?', 'Use JPG for standard photos, PNG for transparency or crisp graphics, and WebP when you want a modern web-friendly format with strong compression.'],
    ['Can I use it on mobile devices?', 'Yes, the tool works on smartphones, tablets, and desktop browsers.'],
    ['Is this tool useful for SEO?', 'Yes. Smaller image files help pages load faster, which improves user experience and can support better SEO performance.'],
    ['Can I compress images for ecommerce?', 'Yes. Smaller product images are useful for stores because they load faster and are easier to place on product pages, category pages, and ads.'],
    ['Can WordPress sites benefit from image compression?', 'Yes. WordPress sites often gain speed improvements when large uploads are compressed before or after publishing.'],
    ['What is the best image format for social media?', 'It depends on the platform, but compressed JPG or WebP works well for most social images, while PNG is better for graphics that need transparency.'],
    ['Are uploaded files stored?', 'Files are processed for the task and are not intended for permanent storage on the platform.'],
    ['Can I compress multiple images one by one?', 'Yes. Upload each file and compress them separately for quick optimization.'],
    ['Why is image optimization important for mobile visitors?', 'Mobile users often have slower connections, so smaller images help pages load faster and feel smoother to use.'],
    ['Should I compress before uploading to my website?', 'Yes. Compressing before upload helps reduce server storage use and gives you more control over the final file size.'],
  ],
  'image-resizer': [
    ['What is an image resizer?', 'An image resizer changes the width and height of a picture so it fits a specific layout, platform, or display requirement.'],
    ['Can I resize images to exact pixels?', 'Yes, this resize image online free tool lets you enter exact width and height in pixels for websites, social media, ecommerce, and documents.'],
    ['Will aspect ratio be maintained?', 'You can keep image proportions while resizing to avoid stretched or distorted results. If you change both dimensions manually, the output follows those exact values.'],
    ['What is aspect ratio?', 'Aspect ratio is the relationship between width and height. Common ratios include 1:1, 4:3, 16:9, and 9:16.'],
    ['What file types can I resize?', 'You can resize common formats like JPG, PNG, and WebP in this browser-based image resizer.'],
    ['Does resizing reduce quality?', 'If you enlarge a small image too much, quality can soften. Downsizing usually keeps the image sharper and lighter.'],
    ['Can I resize photos for social media?', 'Yes. Image resizing is useful for feed posts, stories, thumbnails, and cover images on major social platforms.'],
    ['Can I resize images for ecommerce?', 'Yes. Resized product photos load faster and fit better inside storefront layouts, product cards, and marketplace listings.'],
    ['Should I resize or compress first?', 'When possible, resize first and then compress. That usually gives the best balance of clarity and file size.'],
    ['Is this image resizer free?', 'Yes. You can resize images online for free without signup.'],
    ['Can I use it on mobile?', 'Yes. The tool works on modern mobile browsers as well as desktop browsers.'],
    ['What is the best size for website images?', 'The best size depends on the layout, but website images should match the actual display area instead of being much larger.'],
    ['What size should social media images be?', 'Each platform uses different image sizes, and using the recommended dimensions helps avoid cropping or blurriness.'],
    ['Can I resize JPG and PNG files?', 'Yes. JPG, PNG, and WebP are all supported by the image resizer workflow.'],
    ['Are uploaded files stored?', 'Files are processed for the task and are not intended for permanent storage on the platform.'],
  ],
  'image-format-converter': [
    ['What is an image format converter?', 'An image format converter changes one image type into another, such as JPG to PNG or PNG to WebP, so the file better fits a platform, workflow, or performance goal.'],
    ['Which formats can I convert?', 'This image format converter online free supports PNG, JPG, WebP, and AVIF conversion. You can switch formats for compatibility, quality preference, or smaller file size. It is useful for web uploads, social media posting, and app asset preparation.'],
    ['Do I need to install software?', 'No software is required because the image format converter runs directly in your browser. You can upload, convert, and download in one workflow without signup. This saves time and works well on both desktop and mobile browsers.'],
    ['Can I preview before downloading?', 'Yes, you can preview the uploaded image before converting to another format. This helps confirm the selected file and avoid wrong exports. After conversion, download the final image in your selected format immediately.'],
    ['Can I convert JPG to PNG?', 'Yes. JPG to PNG conversion is common when you need transparency or better graphic handling.'],
    ['Can I convert PNG to JPG?', 'Yes. PNG to JPG conversion is often used to reduce file size for photos without needing transparency.'],
    ['Can I convert WebP to JPG?', 'Yes. WebP to JPG is useful when compatibility with older software matters.'],
    ['Can I convert image online for free?', 'Yes. You can convert image online for free without signup.'],
    ['Is AVIF supported?', 'Yes. AVIF is useful for modern compression workflows, depending on browser support.'],
    ['What is the best format for websites?', 'WebP is often the best balance for modern websites because it is efficient and supports transparency.'],
    ['What is the best format for printing?', 'JPG and PNG are commonly used, but the best choice depends on the source image and desired quality.'],
    ['Are uploaded files stored permanently?', 'Files are processed for the task and are not intended for permanent storage on the platform.'],
    ['Will conversion reduce quality?', 'Some formats use more compression than others, so quality can change depending on the selected output format.'],
    ['Can I use it on mobile?', 'Yes. The image format converter works in modern mobile browsers.'],
    ['What is the best format for logos?', 'PNG is often preferred for logos because it can preserve sharp edges and transparency.'],
  ],
  'image-cropper': [
    ['Which image types can I crop?', 'You can upload and crop JPG, PNG, WebP, and AVIF images.'],
    ['Can I set fixed aspect ratios?', 'Yes. Presets like 1:1, 4:3, 16:9, 3:2, and 9:16 are available.'],
    ['Does this tool support instant download?', 'Yes. After selecting area, click crop and download in PNG, JPG, or WebP.'],
  ],
  'image-to-pdf': [
    ['What is an image to PDF converter?', 'An image to PDF converter turns one or more image files into a PDF document so they are easier to share, print, and archive.'],
    ['Can I convert multiple images into one PDF?', 'Yes. Upload multiple images and combine them into a single PDF file.'],
    ['Do I need to install software?', 'No. The conversion runs online in your browser.'],
    ['Is this image to PDF converter free?', 'Yes. You can convert images to PDF for free without signup.'],
    ['Can I convert JPG to PDF online?', 'Yes. JPG to PDF is one of the most common uses for this tool.'],
    ['Can I convert PNG to PDF?', 'Yes. PNG images can be combined into a PDF document as well.'],
    ['What image formats are best?', 'JPG, PNG, and WebP are the most common formats for image to PDF conversion.'],
    ['Can I create a PDF from scans?', 'Yes. Scanned documents are often saved as PDF because the format is ideal for sharing and archiving.'],
    ['Can I make a photo into a PDF?', 'Yes. Photos can be converted into a PDF as single pages or combined into one document.'],
    ['Can I use it on mobile?', 'Yes. The online image to PDF converter works in modern mobile browsers.'],
    ['Are uploaded files stored permanently?', 'Files are processed for the task and are not intended for permanent storage on the platform.'],
    ['Does PDF preserve image quality?', 'The PDF keeps the image content, but final quality depends on the source image resolution and conversion settings.'],
    ['Can I combine images into one PDF?', 'Yes. Combining multiple images into one PDF is one of the main use cases.'],
    ['Why is PDF better for sharing?', 'PDF is easier to open consistently across devices and is better suited for printing and official sharing.'],
    ['Can I use it for receipts and invoices?', 'Yes. Receipts and invoices are often saved as PDFs for better organization and sharing.'],
  ],
  'json-formatter': [
    ['Can this tool validate invalid JSON?', 'Yes. It checks JSON structure and highlights issues when formatting fails.'],
    ['Can I minify JSON as well?', 'Yes. You can beautify for readability or minify for compact output.'],
    ['Is my JSON data stored?', 'No account is required, and formatting is handled directly in the tool interface.'],
  ],
  'password-generator': [
    ['Does this generator create strong passwords?', 'Yes. It creates random passwords with letters, numbers, and symbols.'],
    ['Can I control password length?', 'Yes. You can choose your preferred password length before generating.'],
    ['Are generated passwords saved?', 'No. Passwords are generated instantly and are not stored by the tool.'],
  ],
  'pdf-compressor': [
    ['What is a PDF compressor?', 'A PDF compressor reduces PDF file size by optimizing images, fonts, metadata, and internal objects so the document becomes easier to email, upload, and store.'],
    ['How does PDF compression work?', 'The tool processes the document structure, removes unnecessary weight where possible, and produces a smaller PDF file that still keeps the content readable.'],
    ['Will text quality remain readable?', 'Yes. The goal is to keep text readable while reducing file size, although the result depends on the source document and how heavily it is compressed.'],
    ['Can I compress large PDF files?', 'Yes. Large PDFs are one of the main use cases for online PDF compression, especially scanned reports, manuals, and presentations.'],
    ['Can I use this PDF compressor for free?', 'Yes. You can reduce PDF file size online free without signup.'],
    ['Is this tool useful for email attachments?', 'Yes. Smaller PDFs are easier to send by email and less likely to run into attachment limits.'],
    ['Can students use it for assignments?', 'Yes. Students often use PDF compression before uploading coursework, reports, and research files.'],
    ['Why do PDFs become so large?', 'PDFs become large when they include high-resolution images, embedded fonts, repeated objects, and extra metadata.'],
    ['Should I compress before uploading to cloud storage?', 'Yes. Smaller PDFs save storage space and make cloud sharing faster and cleaner.'],
    ['What is the best compression level?', 'The best level depends on the document, but a balanced setting usually works well for everyday business and academic files.'],
    ['Does compression change the number of pages?', 'No. Compression reduces file size, not page count.'],
    ['Can I compress scanned documents?', 'Yes. Scanned PDFs are often the best candidates because images inside the document can be optimized.'],
    ['Are uploaded files stored permanently?', 'Files are processed for the task and are not intended for permanent storage on the platform.'],
    ['Should I use ZIP instead of PDF compression?', 'Use PDF compression when you need one smaller PDF file. Use ZIP only when you want to bundle many files together without changing the document itself.'],
    ['Can businesses use this tool for document workflows?', 'Yes. Businesses use PDF compression for invoices, contracts, reports, and internal document sharing.'],
  ],
  'pdf-merge': [
    ['What is a PDF merger?', 'A PDF merger combines separate PDF files into one document so you can organize related pages, simplify sharing, and reduce file clutter.'],
    ['Can I merge multiple PDF files at once?', 'Yes, you can merge PDF files online free by uploading multiple documents in one go and combining them into a single PDF.'],
    ['Can I change file order before merge?', 'Yes. Keeping files in the right order is important because the final merged PDF follows the same sequence.'],
    ['Do I need to install software?', 'No. This online PDF merger works in your browser without desktop software or signup.'],
    ['Is there a watermark on the merged file?', 'No. The merged output is designed to be clean and ready for use.'],
    ['Can I merge reports and invoices?', 'Yes. Reports, invoices, and other business documents are common use cases for a PDF merger.'],
    ['Can students use this tool for assignments?', 'Yes. Students often merge notes, scanned pages, and project files into one submission-ready PDF.'],
    ['Can I combine legal documents?', 'Yes. Legal packets, contracts, and attachments are often merged into one file for easier review.'],
    ['Does merging reduce file size?', 'Not always. PDF merge joins files together, while compression reduces size. Use compression separately if the file is too large.'],
    ['Can I merge cloud files after download?', 'Yes. You can download merged files and upload them to cloud storage or document portals as needed.'],
    ['Can I merge image-based PDF files?', 'Yes. Scanned PDFs and image-based pages can usually be merged together without issue.'],
    ['What if I need to compress the merged PDF?', 'If the final merged PDF is too large, use a PDF compressor after merging.'],
    ['Are uploaded files stored permanently?', 'Files are processed for the task and are not intended for permanent storage on the platform.'],
    ['Can I use this on mobile?', 'Yes. The tool works in modern mobile browsers as well as desktop browsers.'],
    ['Should I merge or compress first?', 'If your documents are separate, merge first. If the final file is too large, compress after merging.'],
  ],
  'qr-generator': [
    ['What is a QR code generator?', 'A QR code generator creates scannable codes that store information such as URLs, text, contact data, and WiFi credentials.'],
    ['What can I create QR codes for?', 'You can generate QR codes for links, text, contact data, and WiFi details.'],
    ['Can I download the generated QR code?', 'Yes. The tool provides a downloadable QR image.'],
    ['Is account signup required?', 'No. You can generate QR codes instantly without signup.'],
    ['Can I create a QR code for a website?', 'Yes. URL QR codes are one of the most common types and are widely used for websites and landing pages.'],
    ['Can I make a WiFi QR code?', 'Yes. A WiFi QR code can store network name and password details for easy scanning.'],
    ['What is the difference between static and dynamic QR codes?', 'Static QR codes contain fixed data, while dynamic QR codes can be changed or tracked after creation.'],
    ['Can QR codes be used for business cards?', 'Yes. Contact QR codes and vCard QR codes are often used on business cards.'],
    ['Can I use QR codes for restaurants?', 'Yes. Restaurants often use QR codes for menus, ordering, and contactless access.'],
    ['Do QR codes work on mobile?', 'Yes. Most modern phones can scan QR codes directly through the camera app.'],
    ['Are QR codes secure?', 'QR codes are useful, but users should still verify the destination before opening any link.'],
    ['Can I use them for ecommerce?', 'Yes. QR codes are commonly used for product pages, promotions, packaging, and support links.'],
    ['Should QR codes be high contrast?', 'Yes. High contrast between the code and background improves scan reliability.'],
    ['Are uploaded or generated codes stored?', 'Generated content is handled for the task and is not intended for permanent storage on the platform.'],
    ['Can I use QR codes in marketing campaigns?', 'Yes. Marketing teams use QR codes to drive traffic, collect leads, and connect offline media with online pages.'],
  ],
  'word-counter': [
    ['What does this word counter measure?', 'It counts words, characters, sentences, and paragraphs in your text.'],
    ['What is a word counter?', 'A word counter is a text analysis tool that measures how much text you have written and helps you stay within length requirements.'],
    ['How does an online word counter work?', 'It processes the text you paste into the box and calculates counts instantly in your browser.'],
    ['Who can use this tool?', 'Writers, students, marketers, SEO users, copywriters, and social media managers can all use it.'],
    ['What is a character counter?', 'A character counter measures the number of letters, spaces, and punctuation marks in a piece of text.'],
    ['What is a sentence counter?', 'A sentence counter estimates how many complete sentences are in your text.'],
    ['What is a paragraph counter?', 'A paragraph counter counts blocks of text separated by line breaks.'],
    ['Do counts update in real time?', 'Yes. The stats update as you type or paste content.'],
    ['Can I count words online for free?', 'Yes. This online word counter is free to use without signup.'],
    ['Can students use it for essays?', 'Yes. It is useful for essay word counts, assignments, and research writing.'],
    ['Can bloggers use it for SEO content?', 'Yes. Bloggers often use word counters to keep article length consistent and structured.'],
    ['Can I check social media limits with it?', 'Yes. It helps you keep text within common character limits for posts and bios.'],
    ['Does it count spaces?', 'The tool counts spaces as part of character totals, and also shows counts that focus on the written text itself.'],
    ['Is this useful for email marketing?', 'Yes. Email subject lines, previews, and body copy can all be checked against length targets.'],
    ['Are pasted texts stored?', 'The content is processed locally in the browser for counting and is not intended for long-term storage.'],
  ],
  'word-to-pdf': [
    ['What is a Word to PDF converter?', 'A Word to PDF converter turns DOC and DOCX files into PDF documents so they are easier to share, print, and archive.'],
    ['Can I convert DOCX to PDF online?', 'Yes. Upload DOC or DOCX files and convert them to PDF online.'],
    ['Will formatting stay intact?', 'The converter is designed to preserve layout, fonts, spacing, and page structure as much as possible.'],
    ['Is Word to PDF conversion free?', 'Yes. You can convert files for free without signup.'],
    ['What is the difference between DOC and DOCX?', 'DOC is the older Word format, while DOCX is the newer XML-based format used by modern Microsoft Word versions.'],
    ['Why save Word as PDF?', 'PDF is better for sharing because it is more portable and usually displays the same on different devices.'],
    ['Can I convert Microsoft Word to PDF?', 'Yes. Microsoft Word files, including DOC and DOCX, are common inputs for this tool.'],
    ['Does PDF keep formatting better than Word?', 'PDF is usually more consistent because the layout becomes fixed and does not change with different software or fonts.'],
    ['Can I use it for resumes?', 'Yes. PDFs are the preferred format for resumes and CVs because they look consistent to recruiters.'],
    ['Can I use it for official documents?', 'Yes. PDFs are widely used for contracts, forms, and official document sharing.'],
    ['Should students submit assignments as PDF?', 'Yes. PDFs are often easier for teachers and LMS platforms to open consistently.'],
    ['Can I convert DOC online on mobile?', 'Yes. The online document converter works in modern mobile browsers.'],
    ['Are uploaded files stored permanently?', 'Files are processed for the task and are not intended for permanent storage on the platform.'],
    ['Will the output be printable?', 'Yes. PDF is one of the best formats for printing and archiving.'],
    ['Can I convert Word documents with images?', 'Yes. Documents with images, tables, and headings can usually be converted successfully.'],
  ],
  'youtube-downloader': [
    ['How do I download a YouTube video?', 'Paste the video URL, fetch available formats, and download your preferred quality.'],
    ['Can I download YouTube Shorts?', 'Yes. Shorts links are supported when a valid URL is provided.'],
    ['Do I need to install any app?', 'No. The downloader works online in your browser.'],
  ],
  'youtube-thumbnail': [
    ['How can I get a YouTube thumbnail?', 'Paste the video URL to load and download available thumbnail resolutions.'],
    ['Can I download HD thumbnail quality?', 'Yes. HD and multiple size options are available when provided by YouTube.'],
    ['Is this thumbnail downloader free?', 'Yes. You can download thumbnails without signup.'],
  ],
};
